---
#System Settings
php_modules: [ 'php7.4-curl', 'php7.4-gd', 'php7.4-mbstring', 'php7.4-xml', 'php7.4-xmlrpc', 'php7.4-soap', 'php7.4-intl', 'php7.4-zip' ]

#MySQL Settings
mysql_root_password: "root"
mysql_db: "wordpress"
mysql_user: "wordpress"
mysql_password: "password"

#HTTP Settings
http_host: "13.127.136.16"
http_conf: "13.127.136.16.conf"
http_port: "80"
